/**
 * @fileoverview Zod schemas and TypeScript types for AI Analyst chat API.
 * Validates UIMessage format from Vercel AI SDK 5.0+.
 * @see https://ai-sdk.dev/docs/reference/ai-sdk-core/ui-message
 */

import { z } from "zod";

// ============================================================================
// Message Part Schemas (AI SDK 5.0+ UIMessage.parts)
// ============================================================================

/** Text part - the most common message part */
export const TextPartSchema = z.object({
  type: z.literal("text"),
  text: z.string(),
});

/** Reasoning/thinking part - from extended thinking */
export const ReasoningPartSchema = z.object({
  type: z.literal("reasoning"),
  text: z.string(),
});

/** File part - generated files or user uploads */
export const FilePartSchema = z.object({
  type: z.literal("file"),
  url: z.string(),
  mediaType: z.string(),
  filename: z.string().optional(),
});

/** Image part - user-attached images (base64 encoded) */
export const ImagePartSchema = z.object({
  type: z.literal("image"),
  data: z.string(), // base64 encoded
  mediaType: z.string(),
});

/** Tool invocation part - when model calls a tool */
export const ToolInvocationPartSchema = z.object({
  type: z.literal("tool-invocation"),
  toolCallId: z.string(),
  toolName: z.string(),
  state: z.enum(["call", "partial-call"]),
  args: z.record(z.string(), z.unknown()),
});

/** Tool result part - result from tool execution */
export const ToolResultPartSchema = z.object({
  type: z.literal("tool-result"),
  toolCallId: z.string(),
  state: z.enum(["result", "error"]),
  result: z.unknown(),
});

/** Dynamic tool part - AI SDK's format for tool calls with results */
export const DynamicToolPartSchema = z.object({
  type: z.literal("dynamic-tool"),
  toolCallId: z.string(),
  toolName: z.string(),
  state: z.enum([
    "input-streaming",
    "input-available",
    "approval-requested",
    "approval-responded",
    "output-available",
    "output-error",
    "output-denied",
  ]),
  input: z.unknown().optional(),
  output: z.unknown().optional(),
  errorText: z.string().optional(),
  title: z.string().optional(),
  providerExecuted: z.boolean().optional(),
});

/** Union of all known message part types */
export const MessagePartSchema = z.discriminatedUnion("type", [
  TextPartSchema,
  ReasoningPartSchema,
  FilePartSchema,
  ImagePartSchema,
  ToolInvocationPartSchema,
  ToolResultPartSchema,
  DynamicToolPartSchema,
]);

// ============================================================================
// UIMessage Schema
// ============================================================================

/** UIMessage schema - validates incoming messages from client */
export const UIMessageSchema = z.object({
  id: z.string(),
  role: z.enum(["system", "user", "assistant"]),
  parts: z.array(MessagePartSchema),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

export type UIMessageType = z.infer<typeof UIMessageSchema>;

// ============================================================================
// Chat Request Schema
// ============================================================================

/** Schema for template files uploaded to container */
export const TemplateFileSchema = z.object({
  name: z.string(),
  content: z.string(), // base64 encoded
  mimeType: z.string(),
});

/** Request body schema for /api/chat endpoint */
export const ChatRequestSchema = z.object({
  messages: z.array(UIMessageSchema).min(1, "At least one message required"),
  caseId: z.string().uuid("Invalid case ID format"),
  containerId: z.string().nullish(), // nullish = null | undefined
  selectedTags: z.array(z.string()).optional(),
  /** Template files to upload on first message (Excel, Word, PDF, etc.) */
  templateFiles: z.array(TemplateFileSchema).optional(),
  /** Enable extended thinking - gives Claude a thinking budget for deeper reasoning */
  extendedThinking: z.boolean().optional(),
});

export type ChatRequest = z.infer<typeof ChatRequestSchema>;

// ============================================================================
// Response Types (for first message - Anthropic SDK)
// ============================================================================

/** Bash code execution output - file generated by bash execution */
export interface BashCodeExecutionOutput {
  type: "bash_code_execution_output";
  file_id: string;
  /** Original filename (may not be present in Anthropic response) */
  filename?: string;
  /** Supabase signed URL for download (added by our API after saving to storage) */
  downloadUrl?: string;
}

/** Anthropic content block types returned by first message API */
export type AnthropicContentBlock =
  | { type: "text"; text: string }
  | { type: "thinking"; thinking: string }
  | {
      type: "server_tool_use";
      id: string;
      name: string;
      input: Record<string, unknown>;
    }
  | {
      type: "server_tool_result";
      tool_use_id: string;
      content: unknown;
      is_error?: boolean;
    }
  | {
      type: "bash_code_execution_tool_use";
      id: string;
      input: { command: string };
    }
  | {
      type: "bash_code_execution_tool_result";
      tool_use_id?: string;
      content: {
        type: "bash_code_execution_result" | "bash_code_execution_error";
        stdout?: string;
        stderr?: string;
        return_code?: number;
        content?: BashCodeExecutionOutput[];
      };
    }
  | {
      type: "text_editor_code_execution_tool_use";
      id: string;
      input: { command: string; path?: string; file_text?: string; new_str?: string };
    }
  | {
      type: "text_editor_code_execution_tool_result";
      tool_use_id?: string;
      content: {
        type: "text_editor_code_execution_result" | "text_editor_code_execution_view_result" | "text_editor_code_execution_create_result";
        file_type?: string;
        content?: string;
        numLines?: number;
      };
    };

/** Response from first message API call (Anthropic SDK, non-streaming) */
export interface FirstMessageResponse {
  id: string;
  containerId: string | null;
  content: AnthropicContentBlock[];
}

// ============================================================================
// Chat Session (localStorage)
// ============================================================================

/**
 * Metadata for a template file uploaded to Claude's container.
 * Only stores display info - actual file goes to Anthropic Files API.
 */
export interface UploadedFile {
  /** Original filename (e.g., "budget.xlsx") */
  name: string;
  /** File size in bytes */
  size: number;
}

/** Chat session stored in localStorage */
export interface ChatSession {
  caseId: string;
  messages: UIMessageType[];
  containerId: string | null;
  /** ISO timestamp when session started (first message sent) */
  startedAt: string;
  /** Selected tag IDs for filtering. Empty array = all tags. */
  selectedTags?: string[];
  /** Template files uploaded to Claude's container (first message only) */
  uploadedFiles?: UploadedFile[];
}

/** LocalStorage key factory */
export const CHAT_STORAGE_KEY = (caseId: string) => `analyst-chat-${caseId}`;

// ============================================================================
// Constants
// ============================================================================

/** Model constant - single source of truth */
export const MODEL_ID = "claude-sonnet-4-5" as const;

// ============================================================================
// Streaming Event Types (for SSE first message)
// ============================================================================

/**
 * Custom metadata event sent at the end of SSE stream.
 * Contains containerId and saved file info needed for follow-up messages.
 */
export interface StreamingMetadataEvent {
  type: "metadata";
  containerId: string | null;
  savedFiles: Array<{
    fileId: string;
    filename: string;
    signedUrl: string;
  }>;
}

/**
 * Anthropic raw streaming event types (subset relevant to our use case).
 * @see https://docs.anthropic.com/en/api/messages-streaming
 */
export type AnthropicStreamEvent =
  | { type: "message_start"; message: { id: string; model: string } }
  | { type: "content_block_start"; index: number; content_block: AnthropicContentBlock }
  | { type: "content_block_delta"; index: number; delta: AnthropicStreamDelta }
  | { type: "content_block_stop"; index: number }
  | { type: "message_delta"; delta: { stop_reason: string }; usage?: { output_tokens: number } }
  | { type: "message_stop" }
  | StreamingMetadataEvent;

/**
 * Delta types for streaming content blocks.
 * Each delta type corresponds to a specific content block type.
 */
export type AnthropicStreamDelta =
  | { type: "text_delta"; text: string }
  | { type: "thinking_delta"; thinking: string }
  | { type: "input_json_delta"; partial_json: string }
  | { type: "bash_code_execution_input_delta"; input_json_delta: string }
  | { type: "text_editor_code_execution_input_delta"; input_json_delta: string };

// ============================================================================
// Constants
// ============================================================================

/** System prompt for analyst chat */
export const SYSTEM_PROMPT = `You are an AI analyst helping users understand their documents.

## Reasoning Process
For analytical questions (not simple lookups), follow this workflow:

**1. Understand**: Before doing anything, make sure you understand the request.
- If the request is vague or could be interpreted multiple ways, ask clarifying questions first
- Identify what output the user actually needs (summary? export? specific data?)

**2. Plan**: For non-trivial analysis, briefly state your approach before executing.
- What data/fields will you query?
- What method will you use (jq, Python, aggregation)?
- What will the output look like?

**3. Confirm**: For expensive operations (full dataset scans, complex transformations, file generation), summarize your plan and wait for user confirmation before proceeding.

**4. Execute**: Run the analysis. Lead with the answer, then explain if needed.

For simple questions ("how many documents?", "what fields exist?"), skip directly to execution.

## File Access
Files uploaded via the conversation are available in your container. On your first response, locate them:
\`\`\`bash
if [ -n "$INPUT_DIR" ] && [ -d "$INPUT_DIR" ]; then
  echo "INPUT_DIR=$INPUT_DIR" && ls -la "$INPUT_DIR"
else
  echo "INPUT_DIR not set, searching..." && find /files /home /tmp . -maxdepth 4 -type f \\( -name "*.json" -o -name "*.csv" -o -name "*.xlsx" \\) 2>/dev/null | head -20
fi
\`\`\`
Use \`$INPUT_DIR\` for reading files and \`$OUTPUT_DIR\` for saving generated files when available.

## Response Style
- Be concise and direct - lead with the answer
- Ask clarifying questions if the request is vague
- Use bullets for lists, bold for emphasis, no emojis

## Guidelines
- Use jq for quick queries, Python/pandas for complex analysis
- Generate files when asked - they'll appear as downloadable attachments
- When outputting files: \`cp report.xlsx "$OUTPUT_DIR/report.xlsx"\` (or current directory if OUTPUT_DIR not set)

## Excel Generation Rules
- **Always prefer .xlsx over .csv** for tabular exports unless the user explicitly requests CSV. Excel preserves data types (dates, numbers, currency) and is more user-friendly.
- **Never write JSON/dictionaries into cells.** Always extract primitive values. For example, if a field contains \`{'amount': 228.6, 'iso_4217_currency_code': 'SGD'}\`, write \`228.6\` to the amount column, not the raw object.
- Format dates as proper Excel dates, not strings
- Format currency amounts with 2 decimal places
- Use human-readable column headers (e.g., "Total Amount" not "total_amount")

## Custom Skills
When generating documents (especially Excel reports), check for custom skill documentation:
\`\`\`bash
if [ -d "/skills" ]; then cat /skills/*/SKILL.md 2>/dev/null; else echo "No custom skills"; fi
\`\`\`
This contains client-specific field definitions, validation rules, and domain context.

## Template Files
The user may attach template files (Excel, Word, PDF, etc.) with their first message. These are output templates you should use when generating reports:
- Read the template to understand the expected structure and formatting
- Populate it with data from the available documents
- Preserve the template's formatting, formulas, and layout where possible
- If the template has headers or placeholders, replace them with actual data`;
